### PR TITLE
setting license as LGPL

### PR DESCRIPTION
**Pull request by drewda**

### CODE REVIEW

**Comment by drewda** [comment]
@zerebubuth please merge when you're ready.

**Comment by zerebubuth** [comment]
Ah, confusion! `LICENSE.md` was a symbolic link to `COPYING`, which was a copy of the MIT license. This change replaces `LICENSE.md`, but not `COPYING`, leaving us with two different licenses. Sorry about that, git probably doesn't make it easy to tell the difference.

Please could you either make the change to `COPYING` only, or to both `COPYING` and `LICENSE.md`?

**Comment by drewda** [comment]
Thanks for noticing, @zerebubuth. Figured it was a small enough edit that I could use the web interface. Will clean this up locally.

**Comment by drewda** [comment]
@zerebubuth have another look, please.

**Comment by zerebubuth** [comment]
I was getting an interesting but confusing new error saying:

```
error: unable to create symlink LICENSE.md (File name too long)
```

Which meant that I wasn't able to check out this branch. It looks like Travis was having the same troubles. Instead I've created #4 which hopefully accomplishes the same goal.

PS: The "autotools" build system requires a file called `COPYING` to be present, so it's best to have both to avoid confusion.

**Comment by zerebubuth** [comment]
Closing in favour of #4.

**Comment by drewda** [comment]
Thanks for the background on Autotools requirements, @zerebubuth.

Yes, that git error is a new and confusing case to me too. A reminder to never use GH's browser based editor for anything more complex than a typo correction in a single file.

**Pull request closed without merging**
